import fs from 'fs';
import path from 'path';
import type { AddonRegistry } from './addon-registry';

// Block content styles shared by the Public UI and the CMSUI. Every add-on's
// `styles/content.css` is aggregated into `.plone/content.css`, which both
// UI loaders import first, inside the `plone-content` cascade layer.
export const CONTENT_STYLESHEET = 'styles/content.css';
export const CONTENT_LAYER = 'plone-content';

function getAddonInfo(addon: string, registry: AddonRegistry) {
  return registry.getAddons().find((a) => a.name === addon);
}

function hasTailwind(addon: string, registry: AddonRegistry) {
  const addonInfo = getAddonInfo(addon, registry);
  if (addonInfo && addonInfo.packageJson) {
    const packageJson = JSON.parse(
      fs.readFileSync(addonInfo.packageJson, 'utf-8'),
    );
    return packageJson.dependencies && packageJson.dependencies['tailwindcss'];
  }
  return false;
}

function header(styleSheetPath: string) {
  return `/*
  Don't change this file manually.
  It is autogenerated by @plone/registry.
  Add a ./${styleSheetPath} in your add-on to load your add-on styles in the app.
  */

`;
}

function buildLoaderCode(registry: AddonRegistry, styleSheetPath: string) {
  const addonsStylesInfo = registry.getAddonStyles(styleSheetPath);

  let buf = header(styleSheetPath);
  buf += `@import './content.css' layer(${CONTENT_LAYER});\n`;

  addonsStylesInfo.forEach((addon) => {
    const customization = `${addon}/${styleSheetPath}`;
    const line = `@import '${customization}';\n`;
    buf += line;

    // Creates an entry `@source 'addonPath';` for each addon if the
    // add-on has tailwindcss as a dependency
    const addonInfo = getAddonInfo(addon, registry);
    if (hasTailwind(addon, registry)) {
      buf += `@source '${addonInfo!.basePath}';\n`;
    }
  });

  return buf;
}

// Block content CSS is plain CSS by contract, so no `@source` entries are
// emitted, and the files don't declare a layer: the UI loaders assign it.
function buildContentLoaderCode(registry: AddonRegistry) {
  const addonsStylesInfo = registry.getAddonStyles(CONTENT_STYLESHEET);

  let buf = header(CONTENT_STYLESHEET);
  addonsStylesInfo.forEach((addon) => {
    buf += `@import '${addon}/${CONTENT_STYLESHEET}';\n`;
  });

  return buf;
}

export function createAddonsStyleLoader(registry: AddonRegistry) {
  const ploneDir = path.join(registry.projectRootPath, '.plone');

  fs.writeFileSync(
    path.join(ploneDir, 'content.css'),
    buildContentLoaderCode(registry),
  );
  fs.writeFileSync(
    path.join(ploneDir, 'publicui.css'),
    buildLoaderCode(registry, 'styles/publicui.css'),
  );
  fs.writeFileSync(
    path.join(ploneDir, 'cmsui.css'),
    buildLoaderCode(registry, 'styles/cmsui.css'),
  );
}

export { buildLoaderCode, buildContentLoaderCode };
