packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'apps/aurora'
  # exclude packages that are inside test directories
  - '!**/test/**'
  # exclude Volto packages, leaving them as reference
  - '!packages/volto*'

publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
  - '*stylelint*'
  - '*cypress*'
  - '*playwright*'

overrides:
  react: ^19.2.0
  react-dom: ^19.2.0
  jotai: ^2.12.5

allowBuilds:
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true
  lightningcss-cli: true
  msgpackr-extract: true
  unrs-resolver: true

# The default pnpm catalog is loaded from `catalog.json` using `.pnpmfile.cjs`.
# If you want to customize the versions of the catalog, do it in there.
