export default function (config) {
  return {
    ...config,
    optimizeDeps: {
      ...config.optimizeDeps,
      include: [
        ...(config.optimizeDeps?.include ?? []),
        '@plone/plate > @platejs/ai/react',
        '@plone/plate > @platejs/basic-nodes',
        '@plone/plate > @platejs/basic-nodes/react',
        '@plone/plate > @platejs/basic-styles',
        '@plone/plate > @platejs/callout',
        '@plone/plate > @platejs/caption',
        '@plone/plate > @platejs/code-block',
        '@plone/plate > @platejs/comment',
        '@plone/plate > @platejs/comment/react',
        '@plone/plate > @platejs/floating',
        '@plone/plate > @platejs/indent',
        '@plone/plate > @platejs/layout',
        '@plone/plate > @platejs/link',
        '@plone/plate > @platejs/link/react',
        '@plone/plate > @platejs/list',
        '@plone/plate > @platejs/list/react',
        '@plone/plate > @platejs/media',
        '@plone/plate > @platejs/mention',
        '@plone/plate > @platejs/selection/react',
        '@plone/plate > @platejs/suggestion',
        '@plone/plate > @platejs/table',
        '@plone/plate > @platejs/table/react',
        '@plone/plate > @platejs/toc',
        '@plone/plate > @platejs/toggle',
        '@plone/plate > @platejs/toggle/react',
        '@plone/plate > @radix-ui/react-avatar',
        '@plone/plate > @radix-ui/react-dropdown-menu',
        '@plone/plate > @radix-ui/react-separator',
        '@plone/plate > @radix-ui/react-slot',
        '@plone/plate > @radix-ui/react-toolbar',
        '@plone/plate > @radix-ui/react-tooltip',
        '@plone/plate > @udecode/cn',
        '@plone/plate > class-variance-authority',
        '@plone/plate > lowlight',
        '@plone/plate > lucide-react',
        '@plone/plate > platejs',
        '@plone/plate > platejs/react',
      ],
    },
  };
}
