export default function (config) {
  return {
    ...config,
    optimizeDeps: {
      ...config.optimizeDeps,
      include: [
        ...(config.optimizeDeps?.include ?? []),
        '@plone/plate > @ai-sdk/react',
        '@plone/plate > @ariakit/react',
        '@plone/plate > @platejs/ai',
        '@plone/plate > @platejs/ai/react',
        '@plone/plate > @platejs/autoformat',
        '@plone/plate > @platejs/basic-nodes',
        '@plone/plate > @platejs/basic-nodes/react',
        '@plone/plate > @platejs/basic-styles',
        '@plone/plate > @platejs/basic-styles/react',
        '@plone/plate > @platejs/callout',
        '@plone/plate > @platejs/callout/react',
        '@plone/plate > @platejs/caption',
        '@plone/plate > @platejs/caption/react',
        '@plone/plate > @platejs/code-block',
        '@plone/plate > @platejs/code-block/react',
        '@plone/plate > @platejs/combobox',
        '@plone/plate > @platejs/combobox/react',
        '@plone/plate > @platejs/comment',
        '@plone/plate > @platejs/comment/react',
        '@plone/plate > @platejs/dnd',
        '@plone/plate > @platejs/docx',
        '@plone/plate > @platejs/emoji/react',
        '@plone/plate > @platejs/floating',
        '@plone/plate > @platejs/indent',
        '@plone/plate > @platejs/indent/react',
        '@plone/plate > @platejs/juice',
        '@plone/plate > @platejs/layout',
        '@plone/plate > @platejs/layout/react',
        '@plone/plate > @platejs/link',
        '@plone/plate > @platejs/link/react',
        '@plone/plate > @platejs/list',
        '@plone/plate > @platejs/list/react',
        '@plone/plate > @platejs/markdown',
        '@plone/plate > @platejs/media',
        '@plone/plate > @platejs/media/react',
        '@plone/plate > @platejs/mention',
        '@plone/plate > @platejs/mention/react',
        '@plone/plate > @platejs/playwright',
        '@plone/plate > @platejs/resizable',
        '@plone/plate > @platejs/selection/react',
        '@plone/plate > @platejs/slash-command/react',
        '@plone/plate > @platejs/suggestion',
        '@plone/plate > @platejs/table',
        '@plone/plate > @platejs/table/react',
        '@plone/plate > @platejs/toc',
        '@plone/plate > @platejs/toc/react',
        '@plone/plate > @platejs/toggle',
        '@plone/plate > @platejs/toggle/react',
        '@plone/plate > @radix-ui/react-alert-dialog',
        '@plone/plate > @radix-ui/react-avatar',
        '@plone/plate > @radix-ui/react-checkbox',
        '@plone/plate > @radix-ui/react-context-menu',
        '@plone/plate > @radix-ui/react-dialog',
        '@plone/plate > @radix-ui/react-dropdown-menu',
        '@plone/plate > @radix-ui/react-popover',
        '@plone/plate > @radix-ui/react-separator',
        '@plone/plate > @radix-ui/react-slot',
        '@plone/plate > @radix-ui/react-toolbar',
        '@plone/plate > @radix-ui/react-tooltip',
        '@plone/plate > @udecode/cn',
        '@plone/plate > ai',
        '@plone/plate > class-variance-authority',
        '@plone/plate > clsx',
        '@plone/plate > cmdk',
        '@plone/plate > html2canvas-pro',
        '@plone/plate > jotai',
        '@plone/plate > lodash.debounce',
        '@plone/plate > lowlight',
        '@plone/plate > lucide-react',
        '@plone/plate > pdf-lib',
        '@plone/plate > platejs',
        '@plone/plate > platejs/react',
        '@plone/plate > react-dnd',
        '@plone/plate > react-dnd-html5-backend',
        '@plone/plate > react-lite-youtube-embed',
        '@plone/plate > remark-gfm',
        '@plone/plate > sonner',
        '@plone/plate > tailwind-merge',
        '@plone/plate > use-file-picker',
        '@plone/plate > zod',
      ],
    },
  };
}
