import type { ConfigType } from '@plone/registry';
export { default as Icon } from './components/Icon/Icon';
import AddIcon from './icons/add.svg?react';
import AlignCenterIcon from './icons/align-center.svg?react';
import AlignLeftIcon from './icons/align-left.svg?react';
import AlignRightIcon from './icons/align-right.svg?react';
import ArchiveIcon from './icons/archive.svg?react';
import ArrowDownIcon from './icons/arrow-down.svg?react';
import ArrowLeftIcon from './icons/arrow-left.svg?react';
import ArrowRightIcon from './icons/arrow-right.svg?react';
import ArrowToprightIcon from './icons/arrow-topright.svg?react';
import ArrowUpIcon from './icons/arrow-up.svg?react';
import AttachmentIcon from './icons/attachment.svg?react';
import AutomatedContentIcon from './icons/automated-content.svg?react';
import BackgroundIcon from './icons/background.svg?react';
import BinIcon from './icons/bin.svg?react';
import BlindIcon from './icons/blind.svg?react';
import BoldIcon from './icons/bold.svg?react';
import CalendarIcon from './icons/calendar.svg?react';
import CheckboxIcon from './icons/checkbox.svg?react';
import ChevronDownIcon from './icons/chevron-down.svg?react';
import ChevronLeftIcon from './icons/chevron-left.svg?react';
import ChevronRightIcon from './icons/chevron-right.svg?react';
import ChevronUpIcon from './icons/chevron-up.svg?react';
import CloseIcon from './icons/close.svg?react';
import CodeIcon from './icons/code.svg?react';
import CollectionIcon from './icons/collection.svg?react';
import ColumnAfterIcon from './icons/column-after.svg?react';
import ColumnBeforeIcon from './icons/column-before.svg?react';
import ColumnDeleteIcon from './icons/column-delete.svg?react';
import ColumnsIcon from './icons/columns.svg?react';
import CopyIcon from './icons/copy.svg?react';
import CutIcon from './icons/cut.svg?react';
import DashIcon from './icons/dash.svg?react';
import DiscussionIcon from './icons/discussion.svg?react';
import DraggableIcon from './icons/draggable.svg?react';
import EditIcon from './icons/edit.svg?react';
import EyeIcon from './icons/eye.svg?react';
import FilterIcon from './icons/filter.svg?react';
import FolderIcon from './icons/folder.svg?react';
import FooterIcon from './icons/footer.svg?react';
import ForegroundIcon from './icons/foreground.svg?react';
import FullscreenIcon from './icons/fullscreen.svg?react';
import HighlightIcon from './icons/highlight.svg?react';
import HistoryIcon from './icons/history.svg?react';
import HomeIcon from './icons/home.svg?react';
import ImageFitIcon from './icons/image-fit.svg?react';
import ImageFullIcon from './icons/image-full.svg?react';
import ImageLeftIcon from './icons/image-left.svg?react';
import ImageNarrowIcon from './icons/image-narrow.svg?react';
import ImageRightIcon from './icons/image-right.svg?react';
import ImageIcon from './icons/image.svg?react';
import ImageWideIcon from './icons/image-wide.svg?react';
import InfoIcon from './icons/info.svg?react';
import ItalicIcon from './icons/italic.svg?react';
import LanguageIcon from './icons/language.svg?react';
import LeadingImageIcon from './icons/leading-image.svg?react';
import LeadingIcon from './icons/leading.svg?react';
import LinkIcon from './icons/link.svg?react';
import ListNumbersIcon from './icons/list-numbers.svg?react';
import ListIcon from './icons/list.svg?react';
import MailIcon from './icons/mail.svg?react';
import MandatoryIcon from './icons/mandatory.svg?react';
import MapIcon from './icons/map.svg?react';
import MenuIcon from './icons/menu.svg?react';
import MergedIcon from './icons/merged.svg?react';
import MoreOptionsIcon from './icons/more-options.svg?react';
import NavigationIcon from './icons/navigation.svg?react';
import NewsIcon from './icons/news.svg?react';
import OutIcon from './icons/out.svg?react';
import PageIcon from './icons/page.svg?react';
import ParagraphIcon from './icons/paragraph.svg?react';
import PasteIcon from './icons/paste.svg?react';
import PauseIcon from './icons/pause.svg?react';
import PencilIcon from './icons/pencil.svg?react';
import PlayIcon from './icons/play.svg?react';
import PropertiesIcon from './icons/properties.svg?react';
import QuotesIcon from './icons/quotes.svg?react';
import RadiobuttonIcon from './icons/radiobutton.svg?react';
import RedoIcon from './icons/redo.svg?react';
import RenameIcon from './icons/rename.svg?react';
import ReverseIcon from './icons/reverse.svg?react';
import ReviewIcon from './icons/review.svg?react';
import RowAfterIcon from './icons/row-after.svg?react';
import RowBeforeIcon from './icons/row-before.svg?react';
import RowDeleteIcon from './icons/row-delete.svg?react';
import SearchIcon from './icons/search.svg?react';
import SecurityIcon from './icons/security.svg?react';
import SettingsIcon from './icons/settings.svg?react';
import ShareIcon from './icons/share.svg?react';
import SliderIcon from './icons/slider.svg?react';
import SocialIcon from './icons/social.svg?react';
import SpacerIcon from './icons/spacer.svg?react';
import StateIcon from './icons/state.svg?react';
import SubtitleIcon from './icons/subtitle.svg?react';
import TableIcon from './icons/table.svg?react';
import TagIcon from './icons/tag.svg?react';
import TextIcon from './icons/text.svg?react';
import ThumbnailsIcon from './icons/thumbnails.svg?react';
import TitleIcon from './icons/title.svg?react';
import TocIcon from './icons/toc.svg?react';
import UndoIcon from './icons/undo.svg?react';
import UploadIcon from './icons/upload.svg?react';
import UserIcon from './icons/user.svg?react';
import VideoIcon from './icons/video.svg?react';
import VoltoIcon from './icons/volto.svg?react';
import WidthDefaultIcon from './icons/width-default.svg?react';
import WidthFullIcon from './icons/width-full.svg?react';
import WidthLayoutIcon from './icons/width-layout.svg?react';
import WidthNarrowIcon from './icons/width-narrow.svg?react';
import WindowedIcon from './icons/windowed.svg?react';
import WorldIcon from './icons/world.svg?react';

export default function install(config: ConfigType) {
  config.registerIcon('add', AddIcon);
  config.registerIcon('alignCenter', AlignCenterIcon);
  config.registerIcon('alignLeft', AlignLeftIcon);
  config.registerIcon('alignRight', AlignRightIcon);
  config.registerIcon('archive', ArchiveIcon);
  config.registerIcon('arrowDown', ArrowDownIcon);
  config.registerIcon('arrowLeft', ArrowLeftIcon);
  config.registerIcon('arrowRight', ArrowRightIcon);
  config.registerIcon('arrowTopright', ArrowToprightIcon);
  config.registerIcon('arrowUp', ArrowUpIcon);
  config.registerIcon('attachment', AttachmentIcon);
  config.registerIcon('automatedContent', AutomatedContentIcon);
  config.registerIcon('background', BackgroundIcon);
  config.registerIcon('bin', BinIcon);
  config.registerIcon('blind', BlindIcon);
  config.registerIcon('bold', BoldIcon);
  config.registerIcon('calendar', CalendarIcon);
  config.registerIcon('checkbox', CheckboxIcon);
  config.registerIcon('chevronDown', ChevronDownIcon);
  config.registerIcon('chevronLeft', ChevronLeftIcon);
  config.registerIcon('chevronRight', ChevronRightIcon);
  config.registerIcon('chevronUp', ChevronUpIcon);
  config.registerIcon('close', CloseIcon);
  config.registerIcon('code', CodeIcon);
  config.registerIcon('collection', CollectionIcon);
  config.registerIcon('columnAfter', ColumnAfterIcon);
  config.registerIcon('columnBefore', ColumnBeforeIcon);
  config.registerIcon('columnDelete', ColumnDeleteIcon);
  config.registerIcon('columns', ColumnsIcon);
  config.registerIcon('copy', CopyIcon);
  config.registerIcon('cut', CutIcon);
  config.registerIcon('dash', DashIcon);
  config.registerIcon('discussion', DiscussionIcon);
  config.registerIcon('draggable', DraggableIcon);
  config.registerIcon('edit', EditIcon);
  config.registerIcon('eye', EyeIcon);
  config.registerIcon('filter', FilterIcon);
  config.registerIcon('folder', FolderIcon);
  config.registerIcon('footer', FooterIcon);
  config.registerIcon('foreground', ForegroundIcon);
  config.registerIcon('fullscreen', FullscreenIcon);
  config.registerIcon('highlight', HighlightIcon);
  config.registerIcon('history', HistoryIcon);
  config.registerIcon('home', HomeIcon);
  config.registerIcon('imageFit', ImageFitIcon);
  config.registerIcon('imageFull', ImageFullIcon);
  config.registerIcon('imageLeft', ImageLeftIcon);
  config.registerIcon('imageNarrow', ImageNarrowIcon);
  config.registerIcon('imageRight', ImageRightIcon);
  config.registerIcon('image', ImageIcon);
  config.registerIcon('imageWide', ImageWideIcon);
  config.registerIcon('info', InfoIcon);
  config.registerIcon('italic', ItalicIcon);
  config.registerIcon('language', LanguageIcon);
  config.registerIcon('leadingImage', LeadingImageIcon);
  config.registerIcon('leading', LeadingIcon);
  config.registerIcon('link', LinkIcon);
  config.registerIcon('listNumbers', ListNumbersIcon);
  config.registerIcon('list', ListIcon);
  config.registerIcon('mail', MailIcon);
  config.registerIcon('mandatory', MandatoryIcon);
  config.registerIcon('map', MapIcon);
  config.registerIcon('menu', MenuIcon);
  config.registerIcon('merged', MergedIcon);
  config.registerIcon('moreOptions', MoreOptionsIcon);
  config.registerIcon('navigation', NavigationIcon);
  config.registerIcon('news', NewsIcon);
  config.registerIcon('out', OutIcon);
  config.registerIcon('page', PageIcon);
  config.registerIcon('paragraph', ParagraphIcon);
  config.registerIcon('paste', PasteIcon);
  config.registerIcon('pause', PauseIcon);
  config.registerIcon('pencil', PencilIcon);
  config.registerIcon('play', PlayIcon);
  config.registerIcon('properties', PropertiesIcon);
  config.registerIcon('quotes', QuotesIcon);
  config.registerIcon('radiobutton', RadiobuttonIcon);
  config.registerIcon('redo', RedoIcon);
  config.registerIcon('rename', RenameIcon);
  config.registerIcon('reverse', ReverseIcon);
  config.registerIcon('review', ReviewIcon);
  config.registerIcon('rowAfter', RowAfterIcon);
  config.registerIcon('rowBefore', RowBeforeIcon);
  config.registerIcon('rowDelete', RowDeleteIcon);
  config.registerIcon('search', SearchIcon);
  config.registerIcon('security', SecurityIcon);
  config.registerIcon('settings', SettingsIcon);
  config.registerIcon('share', ShareIcon);
  config.registerIcon('slider', SliderIcon);
  config.registerIcon('social', SocialIcon);
  config.registerIcon('spacer', SpacerIcon);
  config.registerIcon('state', StateIcon);
  config.registerIcon('subtitle', SubtitleIcon);
  config.registerIcon('table', TableIcon);
  config.registerIcon('tag', TagIcon);
  config.registerIcon('text', TextIcon);
  config.registerIcon('thumbnails', ThumbnailsIcon);
  config.registerIcon('title', TitleIcon);
  config.registerIcon('toc', TocIcon);
  config.registerIcon('undo', UndoIcon);
  config.registerIcon('upload', UploadIcon);
  config.registerIcon('user', UserIcon);
  config.registerIcon('video', VideoIcon);
  config.registerIcon('volto', VoltoIcon);
  config.registerIcon('widthDefault', WidthDefaultIcon);
  config.registerIcon('widthFull', WidthFullIcon);
  config.registerIcon('widthLayout', WidthLayoutIcon);
  config.registerIcon('widthNarrow', WidthNarrowIcon);
  config.registerIcon('windowed', WindowedIcon);
  config.registerIcon('world', WorldIcon);

  return config;
}
